version: '3.9'

services:
  trunks_leo:
    tty: true
    container_name: trunks_leo
    image: trunks
    command: --config trunks.yaml --acm --qos
    volumes:
      - ./trunks.yaml:/trunks/trunks.yaml
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      st:
        ipv4_address: 10.100.200.2
      gw:
        ipv4_address: 10.0.1.2

  client:
    tty: true
    container_name: client
    image: client
    cap_add:
      - NET_ADMIN
    networks:
      st:
        ipv4_address: 10.100.200.10

  server:
    tty: true
    container_name: server
    image: client
    cap_add:
      - NET_ADMIN
    networks:
      gw:
        ipv4_address: 10.0.1.10

networks:
  st:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.100.200.0/24
  gw:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
